name       : tclcl
version    : 1.20
release    : 2
source     :
    - http://downloads.sourceforge.net/sourceforge/otcl-tclcl/tclcl-src-1.20.tar.gz : 64fd1ec4b1d1c13229e58a7e10bf8422d804c5d3f00221117eafc2aff306dc78
license    : MIT
component  : programming.devel
summary    : a Tcl/C++ interface used by Mash, vic, vat, rtp_play, ns, and nam
description: |
    TclCL (Tcl with classes) is a Tcl/C++ interface used by Mash, vic, vat, rtp_play, ns, and nam. It provides a layer of C++ glue over OTcl.
builddeps  :
    - pkgconfig(tcl)
    - pkgconfig(tk)
    - pkgconfig(xt)
    - pkgconfig(x11)
    - otcl-devel
setup      : |
    %patch -p1 < $pkgfiles/tclcl-1.20-tcl86-compat.patch
    %configure --prefix=%installroot%/usr --with-tk=/usr --enable-static
build      : |
    %make
install    : |
    install -d %installroot%/usr/bin
    install -d %installroot%/usr/include
    install -d %installroot%/usr/lib
    %make_install
