name       : remind
version    : 03.01.15
release    : 1
source     :
    - https://www.roaringpenguin.com/files/download/remind-03.01.15.tar.gz : 8adab4c0b30a556c34223094c5c74779164d5f3b8be66b8039f44b577e678ec1
license    : GPL-2.
component  : office
summary    : A sophisticated calendar and alarm program
description: |
    A sophisticated calendar and alarm program
rundeps  :
    - tcllib
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
