name       : megasync
version    : 3.6.0.0
release    : 6
source     :
    - https://github.com/meganz/MEGAsync/archive/v3.6.0.0_Linux.tar.gz : 4be2ff9e3c0beb7653e269e14802fc0cf82b58cd78b0dbbae469533635cd8ddc
    - https://github.com/meganz/sdk/archive/v3.3.1.tar.gz : da00cbff64eba5b83a98c78347f8def3350fcf2c74ba4d4f03e099e42a1566e6
license    : MEGA LIMITED CODE REVIEW LICENCE
component  : network.clients
summary    : Sync your files to your Mega account.
description: |
    Easy automated syncing between your computers and your MEGA Cloud Drive.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libcares)
    - pkgconfig(libcurl)
    - pkgconfig(libmediainfo)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libsodium)
    - pkgconfig(libuv)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(sqlite3)
    - pkgconfig(zlib)
    - cryptopp-devel
patterns   :
    - nautilus :
        - /usr/lib64/nautilus/
        - /usr/share/icons/hicolor/32x32/emblems/
        - /usr/share/icons/hicolor/64x64/emblems/
setup      : |
    # setup sdk
    cd $workdir/src/MEGASync/mega/
    tar -xf $sources/v3.3.1.tar.gz --strip 1 -C .
    %autogen --without-freeimage

    # setup megasync
    cd $workdir/src/
    %qmake PREFIX="/usr" SUBDIRS+="MEGAShellExtNautilus" MEGA.pro
    lrelease MEGASync/MEGASync.pro
build      : |
    cd $workdir/src/
    %make
install    : |
    # install megasync
    cd $workdir/src/MEGASync/
    %make_install INSTALL_ROOT=$installdir
    install -Dm 755 $workdir/src/MEGASync/megasync $installdir/usr/bin/megasync

    # install nautilus extension without update_cache
    cd $workdir/src/MEGAShellExtNautilus/
    %make install_target install_emblems32 install_emblems64 FORCE INSTALL_ROOT=$installdir
